stages:
 - requirements
 - tests

variables:
  SONAR_SCANNER_VERSION: 5.0.1.3006

requirements_job:
  image: docker.ellisbs.co.uk:5190/ubuntu:24.04
  stage: requirements
  tags:
    - linux
  script:
    - python3 -m venv /tmp/venv
    - source /tmp/venv/bin/activate
    - pip install -r requirements.txt
    - pip freeze
  variables:
    GIT_STRATEGY: clone

test_job:
  image: docker.ellisbs.co.uk:5190/ubuntu:24.04
  stage: tests
  tags:
    - linux
  script:
    - pip install -r requirements.txt
    - python3 -m unittest discover 'tests'
    - ~/.local/bin/coverage run -m unittest discover tests
    - ~/.local/bin/coverage xml
    - rm -rf __pycache__
  variables:
    GIT_STRATEGY: clone
    PYTHONPATH: "${PYTHONPATH}:${CI_PROJECT_DIR}"  # Add project root to Python path
  artifacts:
    paths:
      - coverage.xml
