stages:
 - requirements
 - tests

variables:
  SONAR_SCANNER_VERSION: 5.0.1.3006

requirements_job:
  stage: requirements
  tags:
    - linux
  script:
    - sudo apt-get update
    - sudo rm -rf /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/debconf/*.dat /var/cache/apt/archives/lock
    - sudo dpkg --configure -a
    - sudo apt-get install -f
    - sudo apt-get install -y python3-dev python3-pip libcairo2-dev
    - pip install -r requirements.txt
    - pip freeze
  variables:
    GIT_STRATEGY: clone

test_job:
  stage: tests
  tags:
    - linux
  script:
    - sudo apt-get update
    - sudo rm -rf /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/debconf/*.dat /var/cache/apt/archives/lock
    - sudo dpkg --configure -a
    - sudo apt-get install -f
    - sudo apt-get install -y python3-dev python3-pip libasound2-dev
    - sudo pip install -r requirements.txt
    - sudo ./app_unittest.py
    - sudo ~/.local/bin/coverage run -m unittest -s tests
    - sudo ~/.local/bin/coverage xml
    - sudo rm -rf __pycache__
  artifacts:
    paths:
      - coverage.xml
  variables:
    GIT_STRATEGY: clone
