stages:
 - requirements
 - tests

variables:
  SONAR_SCANNER_VERSION: 5.0.1.3006

requirements_job:
  image: docker.ellisbs.co.uk:5190/ubuntu:24.04
  stage: requirements
  tags:
    - linux
  script:
    - python3 -m venv /tmp/venv
    - source /tmp/venv/bin/activate
    - pip install -r requirements.txt
    - pip freeze
  variables:
    GIT_STRATEGY: clone

test_job:
  image: docker.ellisbs.co.uk:5190/ubuntu:24.04
  stage: tests
  tags:
    - linux
  script:
    - python3 -m venv /tmp/venv
    - source /tmp/venv/bin/activate
    - pip install -r requirements.txt
    - python3 -m unittest discover 'tests'
    - coverage run -m unittest discover tests
    - coverage xml
    - rm -rf __pycache__
  variables:
    GIT_STRATEGY: clone
    PYTHONPATH: "${PYTHONPATH}:${CI_PROJECT_DIR}"  # Add project root to Python path
  artifacts:
    paths:
      - coverage.xml

scan_job:
  image: docker.ellisbs.co.uk:5190/ubuntu:24.04
  stage: scan
  tags:
    - linux
  script:
    - pushd ~
    - curl -o /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip
    - unzip -n /tmp/sonar-scanner.zip
    - popd
    - ~/sonar-scanner-${SONAR_SCANNER_VERSION}/bin/sonar-scanner -Dsonar.token=$SONAR_TOKEN
  dependencies:
    - test_job
  artifacts:
    paths:
      - coverage.xml
  variables:
    GIT_STRATEGY: clone
