repos:
-   repo: local
    hooks:
      - id: evaluate-changes
        name: Evaluate Changes
        entry: python ../pre-commit-chatgpt-config/scripts/evaluate_commit.py
        language: system
        pass_filenames: true
